import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html
            lang="ko"
            className="w-full h-full"
            data-theme="light"
            data-contrast="standard"
        >
            <head>
                <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
            </head>
            <body className="w-full h-full bg-surface flex flex-col justify-start items-center">
                {children}
            </body>
        </html>
    );
}
